version: '3.8'

services:
  db-dapur:
    image: mysql:8.0
    container_name: mbg-db-dapur
    restart: always
    environment:
      MYSQL_DATABASE: db_dapur
      MYSQL_ROOT_PASSWORD: password123
    volumes:
      - db-dapur-data:/var/lib/mysql

  db-menu:
    image: mysql:8.0
    container_name: mbg-db-menu
    restart: always
    environment:
      MYSQL_DATABASE: db_menu
      MYSQL_ROOT_PASSWORD: password123
    volumes:
      - db-menu-data:/var/lib/mysql

  db-sekolah:
    image: mysql:8.0
    container_name: mbg-db-sekolah
    restart: always
    environment:
      MYSQL_DATABASE: db_sekolah
      MYSQL_ROOT_PASSWORD: password123
    volumes:
      - db-sekolah-data:/var/lib/mysql

  db-distribusi:
    image: mysql:8.0
    container_name: mbg-db-distribusi
    restart: always
    environment:
      MYSQL_DATABASE: db_distribusi
      MYSQL_ROOT_PASSWORD: password123
    volumes:
      - db-distribusi-data:/var/lib/mysql

  db-inventory:
    image: mysql:8.0
    container_name: mbg-db-inventory
    restart: always
    environment:
      MYSQL_DATABASE: db_inventory
      MYSQL_ROOT_PASSWORD: password123
    volumes:
      - db-inventory-data:/var/lib/mysql

  service-dapur:
    build: ./service-dapur
    container_name: mbg-service-dapur
    depends_on:
      - db-dapur
    ports:
      - "3001:3001"
    env_file:
      - ./service-dapur/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  service-menu:
    build: ./service-menu
    container_name: mbg-service-menu
    depends_on:
      - db-menu
    ports:
      - "3002:3002"
    env_file:
      - ./service-menu/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  service-sekolah:
    build: ./service-sekolah
    container_name: mbg-service-sekolah
    depends_on:
      - db-sekolah
    ports:
      - "3003:3003"
    env_file:
      - ./service-sekolah/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  service-distribusi:
    build: ./service-distribusi
    container_name: mbg-service-distribusi
    depends_on:
      - db-distribusi
    ports:
      - "3005:3005"
    env_file:
      - ./service-distribusi/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  service-inventory:
    build: ./service-inventory
    container_name: mbg-service-inventory
    depends_on:
      - db-inventory
    ports:
      - "3004:3004"
    env_file:
      - ./service-inventory/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mbg-frontend
    ports:
      - "5501:5501"
    volumes:
      - ./frontend:/app
    restart: always

volumes:
  db-dapur-data:
  db-menu-data:
  db-sekolah-data:
  db-distribusi-data:
  db-inventory-data: